### ISSUE TITLE
CentOS support?

### ISSUE THREAD

**Issue by 4cm4k1** [codercom/sshcode#31]
Hi,

I was just wondering if CentOS support has been tested. I'm attempting to use this, and I get the following error output when starting `code-server`:
```shell
/tmp/codessh-code-server: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/codessh-code-server)
/tmp/codessh-code-server: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/codessh-code-server)
/tmp/codessh-code-server: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/codessh-code-server)
2019-04-22 09:49:09 FATAL	code-server didn't start in time context deadline exceeded
```

**Comment by coadler** [comment]
This is more of a `code-server` issue since `sshcode` just downloads the latest `code-server` release onto the target system. Lots of people have shared the same frustration with CentOS so it's definitely something we're working on

Some related issues from `code-server`: https://github.com/codercom/code-server/issues/239 https://github.com/codercom/code-server/issues/209

**Comment by 4cm4k1** [comment]
Thanks, Colin.
